export const NATURE_FAMILIES = {
  tree: { cost: 60, unlock: 6, radius: 5, cooling: 3, biodiversity: 2, wellbeing: 2, size: 1 },
  grass: { cost: 20, unlock: 6, radius: 3, cooling: 1, biodiversity: 1, wellbeing: 1, size: 1 },
  shrub: { cost: 35, unlock: 15, radius: 4, cooling: 1, biodiversity: 2, wellbeing: 1.5, size: 1 },
  flower: { cost: 30, unlock: 15, radius: 4, cooling: 0.5, biodiversity: 3, wellbeing: 2, size: 1 },
  habitat: { cost: 25, unlock: 15, radius: 4, cooling: 0, biodiversity: 2, wellbeing: 0, size: 1 },
  conifer: { cost: 90, unlock: 32, radius: 6, cooling: 4, biodiversity: 3, wellbeing: 3, size: 1 },
  palm: { cost: 100, unlock: 60, radius: 6, cooling: 3, biodiversity: 3, wellbeing: 3, size: 1 },
} as const;

export type NatureFamily = keyof typeof NATURE_FAMILIES;

export const NATURE_MODELS = [
  ["nature-cactus-short", "nature/cactus_short", "shrub"],
  ["nature-cactus-tall", "nature/cactus_tall", "shrub"],
  ["nature-flower-purpleA", "nature/flower_purpleA", "flower"],
  ["nature-flower-purpleB", "nature/flower_purpleB", "flower"],
  ["nature-flower-purpleC", "nature/flower_purpleC", "flower"],
  ["nature-flower-redA", "nature/flower_redA", "flower"],
  ["nature-flower-redB", "nature/flower_redB", "flower"],
  ["nature-flower-redC", "nature/flower_redC", "flower"],
  ["nature-flower-yellowA", "nature/flower_yellowA", "flower"],
  ["nature-flower-yellowB", "nature/flower_yellowB", "flower"],
  ["nature-flower-yellowC", "nature/flower_yellowC", "flower"],
  ["nature-grass", "nature/grass", "grass"],
  ["nature-grass-large", "nature/grass_large", "grass"],
  ["nature-grass-leafs", "nature/grass_leafs", "grass"],
  ["nature-grass-leafsLarge", "nature/grass_leafsLarge", "grass"],
  ["nature-ground-grass", "nature/ground_grass", "grass"],
  ["nature-lily-large", "nature/lily_large", "flower"],
  ["nature-lily-small", "nature/lily_small", "flower"],
  ["nature-log", "nature/log", "habitat"],
  ["nature-log-large", "nature/log_large", "habitat"],
  ["nature-log-stack", "nature/log_stack", "habitat"],
  ["nature-log-stackLarge", "nature/log_stackLarge", "habitat"],
  ["nature-mushroom-red", "nature/mushroom_red", "flower"],
  ["nature-mushroom-redGroup", "nature/mushroom_redGroup", "flower"],
  ["nature-mushroom-redTall", "nature/mushroom_redTall", "flower"],
  ["nature-mushroom-tan", "nature/mushroom_tan", "flower"],
  ["nature-mushroom-tanGroup", "nature/mushroom_tanGroup", "flower"],
  ["nature-mushroom-tanTall", "nature/mushroom_tanTall", "flower"],
  ["nature-plant-bush", "nature/plant_bush", "shrub"],
  ["nature-plant-bushLarge", "nature/plant_bushLarge", "shrub"],
  ["nature-plant-bushLargeTriangle", "nature/plant_bushLargeTriangle", "shrub"],
  ["nature-plant-bushSmall", "nature/plant_bushSmall", "shrub"],
  ["nature-plant-bushTriangle", "nature/plant_bushTriangle", "shrub"],
  ["nature-plant-flatShort", "nature/plant_flatShort", "shrub"],
  ["nature-plant-flatTall", "nature/plant_flatTall", "shrub"],
  ["nature-rock-largeA", "nature/rock_largeA", "habitat"],
  ["nature-rock-largeB", "nature/rock_largeB", "habitat"],
  ["nature-rock-largeC", "nature/rock_largeC", "habitat"],
  ["nature-rock-largeD", "nature/rock_largeD", "habitat"],
  ["nature-rock-largeE", "nature/rock_largeE", "habitat"],
  ["nature-rock-largeF", "nature/rock_largeF", "habitat"],
  ["nature-rock-smallA", "nature/rock_smallA", "habitat"],
  ["nature-rock-smallB", "nature/rock_smallB", "habitat"],
  ["nature-rock-smallC", "nature/rock_smallC", "habitat"],
  ["nature-rock-smallD", "nature/rock_smallD", "habitat"],
  ["nature-rock-smallE", "nature/rock_smallE", "habitat"],
  ["nature-rock-smallF", "nature/rock_smallF", "habitat"],
  ["nature-rock-smallFlatA", "nature/rock_smallFlatA", "habitat"],
  ["nature-rock-smallFlatB", "nature/rock_smallFlatB", "habitat"],
  ["nature-rock-smallFlatC", "nature/rock_smallFlatC", "habitat"],
  ["nature-rock-smallG", "nature/rock_smallG", "habitat"],
  ["nature-rock-smallH", "nature/rock_smallH", "habitat"],
  ["nature-rock-smallI", "nature/rock_smallI", "habitat"],
  ["nature-rock-smallTopA", "nature/rock_smallTopA", "habitat"],
  ["nature-rock-smallTopB", "nature/rock_smallTopB", "habitat"],
  ["nature-rock-tallA", "nature/rock_tallA", "habitat"],
  ["nature-rock-tallB", "nature/rock_tallB", "habitat"],
  ["nature-rock-tallC", "nature/rock_tallC", "habitat"],
  ["nature-rock-tallD", "nature/rock_tallD", "habitat"],
  ["nature-rock-tallE", "nature/rock_tallE", "habitat"],
  ["nature-rock-tallF", "nature/rock_tallF", "habitat"],
  ["nature-rock-tallG", "nature/rock_tallG", "habitat"],
  ["nature-rock-tallH", "nature/rock_tallH", "habitat"],
  ["nature-rock-tallI", "nature/rock_tallI", "habitat"],
  ["nature-rock-tallJ", "nature/rock_tallJ", "habitat"],
  ["nature-stone-largeA", "nature/stone_largeA", "habitat"],
  ["nature-stone-largeB", "nature/stone_largeB", "habitat"],
  ["nature-stone-largeC", "nature/stone_largeC", "habitat"],
  ["nature-stone-largeD", "nature/stone_largeD", "habitat"],
  ["nature-stone-largeE", "nature/stone_largeE", "habitat"],
  ["nature-stone-largeF", "nature/stone_largeF", "habitat"],
  ["nature-stone-smallA", "nature/stone_smallA", "habitat"],
  ["nature-stone-smallB", "nature/stone_smallB", "habitat"],
  ["nature-stone-smallC", "nature/stone_smallC", "habitat"],
  ["nature-stone-smallD", "nature/stone_smallD", "habitat"],
  ["nature-stone-smallE", "nature/stone_smallE", "habitat"],
  ["nature-stone-smallF", "nature/stone_smallF", "habitat"],
  ["nature-stone-smallFlatA", "nature/stone_smallFlatA", "habitat"],
  ["nature-stone-smallFlatB", "nature/stone_smallFlatB", "habitat"],
  ["nature-stone-smallFlatC", "nature/stone_smallFlatC", "habitat"],
  ["nature-stone-smallG", "nature/stone_smallG", "habitat"],
  ["nature-stone-smallH", "nature/stone_smallH", "habitat"],
  ["nature-stone-smallI", "nature/stone_smallI", "habitat"],
  ["nature-stone-smallTopA", "nature/stone_smallTopA", "habitat"],
  ["nature-stone-smallTopB", "nature/stone_smallTopB", "habitat"],
  ["nature-stone-tallA", "nature/stone_tallA", "habitat"],
  ["nature-stone-tallB", "nature/stone_tallB", "habitat"],
  ["nature-stone-tallC", "nature/stone_tallC", "habitat"],
  ["nature-stone-tallD", "nature/stone_tallD", "habitat"],
  ["nature-stone-tallE", "nature/stone_tallE", "habitat"],
  ["nature-stone-tallF", "nature/stone_tallF", "habitat"],
  ["nature-stone-tallG", "nature/stone_tallG", "habitat"],
  ["nature-stone-tallH", "nature/stone_tallH", "habitat"],
  ["nature-stone-tallI", "nature/stone_tallI", "habitat"],
  ["nature-stone-tallJ", "nature/stone_tallJ", "habitat"],
  ["nature-stump-old", "nature/stump_old", "habitat"],
  ["nature-stump-oldTall", "nature/stump_oldTall", "habitat"],
  ["nature-stump-round", "nature/stump_round", "habitat"],
  ["nature-stump-square", "nature/stump_square", "habitat"],
  ["nature-tree-blocks", "nature/tree_blocks", "tree"],
  ["nature-tree-blocks-dark", "nature/tree_blocks_dark", "tree"],
  ["nature-tree-blocks-fall", "nature/tree_blocks_fall", "tree"],
  ["nature-tree-cone", "nature/tree_cone", "tree"],
  ["nature-tree-cone-dark", "nature/tree_cone_dark", "tree"],
  ["nature-tree-cone-fall", "nature/tree_cone_fall", "tree"],
  ["nature-tree-default", "nature/tree_default", "tree"],
  ["nature-tree-default-dark", "nature/tree_default_dark", "tree"],
  ["nature-tree-default-fall", "nature/tree_default_fall", "tree"],
  ["nature-tree-fat", "nature/tree_fat", "tree"],
  ["nature-tree-fat-darkh", "nature/tree_fat_darkh", "tree"],
  ["nature-tree-fat-fall", "nature/tree_fat_fall", "tree"],
  ["nature-tree-oak", "nature/tree_oak", "tree"],
  ["nature-tree-oak-dark", "nature/tree_oak_dark", "tree"],
  ["nature-tree-oak-fall", "nature/tree_oak_fall", "tree"],
  ["nature-tree-palm", "nature/tree_palm", "palm"],
  ["nature-tree-palmBend", "nature/tree_palmBend", "palm"],
  ["nature-tree-palmShort", "nature/tree_palmShort", "palm"],
  ["nature-tree-palmTall", "nature/tree_palmTall", "palm"],
  ["nature-tree-pineDefaultA", "nature/tree_pineDefaultA", "conifer"],
  ["nature-tree-pineDefaultB", "nature/tree_pineDefaultB", "conifer"],
  ["nature-tree-pineGroundA", "nature/tree_pineGroundA", "conifer"],
  ["nature-tree-pineGroundB", "nature/tree_pineGroundB", "conifer"],
  ["nature-tree-pineRoundA", "nature/tree_pineRoundA", "conifer"],
  ["nature-tree-pineRoundB", "nature/tree_pineRoundB", "conifer"],
  ["nature-tree-pineRoundC", "nature/tree_pineRoundC", "conifer"],
  ["nature-tree-pineRoundD", "nature/tree_pineRoundD", "conifer"],
  ["nature-tree-pineRoundE", "nature/tree_pineRoundE", "conifer"],
  ["nature-tree-pineRoundF", "nature/tree_pineRoundF", "conifer"],
  ["nature-tree-pineSmallA", "nature/tree_pineSmallA", "conifer"],
  ["nature-tree-pineSmallB", "nature/tree_pineSmallB", "conifer"],
  ["nature-tree-pineSmallC", "nature/tree_pineSmallC", "conifer"],
  ["nature-tree-pineSmallD", "nature/tree_pineSmallD", "conifer"],
  ["nature-tree-pineTallA", "nature/tree_pineTallA", "conifer"],
  ["nature-tree-pineTallB", "nature/tree_pineTallB", "conifer"],
  ["nature-tree-pineTallC", "nature/tree_pineTallC", "conifer"],
  ["nature-tree-pineTallD", "nature/tree_pineTallD", "conifer"],
  ["nature-tree-plateau", "nature/tree_plateau", "tree"],
  ["nature-tree-plateau-dark", "nature/tree_plateau_dark", "tree"],
  ["nature-tree-plateau-fall", "nature/tree_plateau_fall", "tree"],
  ["nature-tree-simple", "nature/tree_simple", "tree"],
  ["nature-tree-simple-dark", "nature/tree_simple_dark", "tree"],
  ["nature-tree-simple-fall", "nature/tree_simple_fall", "tree"],
  ["nature-tree-small", "nature/tree_small", "tree"],
  ["nature-tree-small-dark", "nature/tree_small_dark", "tree"],
  ["nature-tree-small-fall", "nature/tree_small_fall", "tree"],
  ["nature-tree-tall", "nature/tree_tall", "tree"],
  ["nature-tree-tall-dark", "nature/tree_tall_dark", "tree"],
  ["nature-tree-tall-fall", "nature/tree_tall_fall", "tree"],
  ["nature-tree-thin", "nature/tree_thin", "tree"],
  ["nature-tree-thin-dark", "nature/tree_thin_dark", "tree"],
  ["nature-tree-thin-fall", "nature/tree_thin_fall", "tree"],
  ["mini-forest-patch-grass", "mini-forest/patch-grass", "grass"],
  ["mini-forest-plant", "mini-forest/plant", "shrub"],
  ["mini-forest-rocks-high", "mini-forest/rocks-high", "habitat"],
  ["mini-forest-rocks-low", "mini-forest/rocks-low", "habitat"],
  ["mini-forest-rocks-ramp", "mini-forest/rocks-ramp", "habitat"],
  ["mini-forest-stones", "mini-forest/stones", "habitat"],
  ["mini-forest-tree", "mini-forest/tree", "conifer"],
  ["mini-forest-tree-high", "mini-forest/tree-high", "conifer"],
  ["pirate-grass", "pirate/grass", "grass"],
  ["pirate-grass-patch", "pirate/grass-patch", "grass"],
  ["pirate-grass-plant", "pirate/grass-plant", "grass"],
  ["pirate-palm-bend", "pirate/palm-bend", "palm"],
  ["pirate-palm-straight", "pirate/palm-straight", "palm"],
  ["pirate-patch-grass", "pirate/patch-grass", "grass"],
  ["pirate-patch-grass-foliage", "pirate/patch-grass-foliage", "grass"],
] as const satisfies readonly (readonly [string, string, NatureFamily])[];

export type NatureType = typeof NATURE_MODELS[number][0];
export type NatureModel = typeof NATURE_MODELS[number];
export const NATURE_TYPES = NATURE_MODELS.map(([type]) => type);
const modelsByType = new Map<string, NatureModel>(NATURE_MODELS.map(model => [model[0], model]));

export function natureModelOf(type: string): NatureModel | undefined {
  return modelsByType.get(type);
}

export function greenProfileOf(type: string) {
  if (type === 'tree') return { radius: 4, cooling: 1, biodiversity: 1, wellbeing: 1 };
  if (type === 'park') return { radius: 6, cooling: 3, biodiversity: 3, wellbeing: 3 };
  const model = natureModelOf(type);
  return model ? NATURE_FAMILIES[model[2]] : undefined;
}
