export const NATURE_FAMILIES = {
  tree: { cost: 60, unlock: 6, radius: 5, cooling: 3, biodiversity: 2, wellbeing: 2, size: 1 },
  grass: { cost: 20, unlock: 6, radius: 3, cooling: 1, biodiversity: 1, wellbeing: 1, size: 1 },
  shrub: { cost: 35, unlock: 15, radius: 4, cooling: 1, biodiversity: 2, wellbeing: 1.5, size: 1 },
  flower: { cost: 30, unlock: 15, radius: 4, cooling: 0.5, biodiversity: 3, wellbeing: 2, size: 1 },
  habitat: { cost: 25, unlock: 15, radius: 4, cooling: 0, biodiversity: 2, wellbeing: 0, size: 1 },
  conifer: { cost: 90, unlock: 32, radius: 6, cooling: 4, biodiversity: 3, wellbeing: 3, size: 1 },
  palm: { cost: 100, unlock: 60, radius: 6, cooling: 3, biodiversity: 3, wellbeing: 3, size: 1 },
} as const;

export type NatureFamily = keyof typeof NATURE_FAMILIES;

export const NATURE_MODELS = [
  ["nature-cactus-short", "nature/cactus_short", "shrub", "Cactus short", "Cactus court"],
  ["nature-cactus-tall", "nature/cactus_tall", "shrub", "Cactus tall", "Cactus haut"],
  ["nature-flower-purpleA", "nature/flower_purpleA", "flower", "Flowers purple A", "Fleurs violettes A"],
  ["nature-flower-purpleB", "nature/flower_purpleB", "flower", "Flowers purple B", "Fleurs violettes B"],
  ["nature-flower-purpleC", "nature/flower_purpleC", "flower", "Flowers purple C", "Fleurs violettes C"],
  ["nature-flower-redA", "nature/flower_redA", "flower", "Flowers red A", "Fleurs rouges A"],
  ["nature-flower-redB", "nature/flower_redB", "flower", "Flowers red B", "Fleurs rouges B"],
  ["nature-flower-redC", "nature/flower_redC", "flower", "Flowers red C", "Fleurs rouges C"],
  ["nature-flower-yellowA", "nature/flower_yellowA", "flower", "Flowers yellow A", "Fleurs jaunes A"],
  ["nature-flower-yellowB", "nature/flower_yellowB", "flower", "Flowers yellow B", "Fleurs jaunes B"],
  ["nature-flower-yellowC", "nature/flower_yellowC", "flower", "Flowers yellow C", "Fleurs jaunes C"],
  ["nature-grass", "nature/grass", "grass", "Grass", "Herbe"],
  ["nature-grass-large", "nature/grass_large", "grass", "Grass large", "Herbe grande"],
  ["nature-grass-leafs", "nature/grass_leafs", "grass", "Grass leafy", "Herbe feuillue"],
  ["nature-grass-leafsLarge", "nature/grass_leafsLarge", "grass", "Grass leafy large", "Herbe feuillue grande"],
  ["nature-ground-grass", "nature/ground_grass", "grass", "low Grass", "bas Herbe"],
  ["nature-lily-large", "nature/lily_large", "flower", "Lily large", "Nénuphar grande"],
  ["nature-lily-small", "nature/lily_small", "flower", "Lily small", "Nénuphar petit"],
  ["nature-log", "nature/log", "habitat", "Log", "Tronc"],
  ["nature-log-large", "nature/log_large", "habitat", "Log large", "Tronc grande"],
  ["nature-log-stack", "nature/log_stack", "habitat", "Log stack", "Tronc tas"],
  ["nature-log-stackLarge", "nature/log_stackLarge", "habitat", "Log stack large", "Tronc tas grande"],
  ["nature-mushroom-red", "nature/mushroom_red", "flower", "Mushrooms red", "Champignons rouges"],
  ["nature-mushroom-redGroup", "nature/mushroom_redGroup", "flower", "Mushrooms red group", "Champignons rouges groupe"],
  ["nature-mushroom-redTall", "nature/mushroom_redTall", "flower", "Mushrooms red tall", "Champignons rouges haut"],
  ["nature-mushroom-tan", "nature/mushroom_tan", "flower", "Mushrooms tan", "Champignons beiges"],
  ["nature-mushroom-tanGroup", "nature/mushroom_tanGroup", "flower", "Mushrooms tan group", "Champignons beiges groupe"],
  ["nature-mushroom-tanTall", "nature/mushroom_tanTall", "flower", "Mushrooms tan tall", "Champignons beiges haut"],
  ["nature-plant-bush", "nature/plant_bush", "shrub", "Plant bush", "Plante buisson"],
  ["nature-plant-bushLarge", "nature/plant_bushLarge", "shrub", "Plant bush large", "Plante buisson grande"],
  ["nature-plant-bushLargeTriangle", "nature/plant_bushLargeTriangle", "shrub", "Plant bush large triangular", "Plante buisson grande triangulaire"],
  ["nature-plant-bushSmall", "nature/plant_bushSmall", "shrub", "Plant bush small", "Plante buisson petit"],
  ["nature-plant-bushTriangle", "nature/plant_bushTriangle", "shrub", "Plant bush triangular", "Plante buisson triangulaire"],
  ["nature-plant-flatShort", "nature/plant_flatShort", "shrub", "Plant flat short", "Plante plat court"],
  ["nature-plant-flatTall", "nature/plant_flatTall", "shrub", "Plant flat tall", "Plante plat haut"],
  ["nature-rock-largeA", "nature/rock_largeA", "habitat", "Rock large A", "Rocher grande A"],
  ["nature-rock-largeB", "nature/rock_largeB", "habitat", "Rock large B", "Rocher grande B"],
  ["nature-rock-largeC", "nature/rock_largeC", "habitat", "Rock large C", "Rocher grande C"],
  ["nature-rock-largeD", "nature/rock_largeD", "habitat", "Rock large D", "Rocher grande D"],
  ["nature-rock-largeE", "nature/rock_largeE", "habitat", "Rock large E", "Rocher grande E"],
  ["nature-rock-largeF", "nature/rock_largeF", "habitat", "Rock large F", "Rocher grande F"],
  ["nature-rock-smallA", "nature/rock_smallA", "habitat", "Rock small A", "Rocher petit A"],
  ["nature-rock-smallB", "nature/rock_smallB", "habitat", "Rock small B", "Rocher petit B"],
  ["nature-rock-smallC", "nature/rock_smallC", "habitat", "Rock small C", "Rocher petit C"],
  ["nature-rock-smallD", "nature/rock_smallD", "habitat", "Rock small D", "Rocher petit D"],
  ["nature-rock-smallE", "nature/rock_smallE", "habitat", "Rock small E", "Rocher petit E"],
  ["nature-rock-smallF", "nature/rock_smallF", "habitat", "Rock small F", "Rocher petit F"],
  ["nature-rock-smallFlatA", "nature/rock_smallFlatA", "habitat", "Rock small flat A", "Rocher petit plat A"],
  ["nature-rock-smallFlatB", "nature/rock_smallFlatB", "habitat", "Rock small flat B", "Rocher petit plat B"],
  ["nature-rock-smallFlatC", "nature/rock_smallFlatC", "habitat", "Rock small flat C", "Rocher petit plat C"],
  ["nature-rock-smallG", "nature/rock_smallG", "habitat", "Rock small G", "Rocher petit G"],
  ["nature-rock-smallH", "nature/rock_smallH", "habitat", "Rock small H", "Rocher petit H"],
  ["nature-rock-smallI", "nature/rock_smallI", "habitat", "Rock small I", "Rocher petit I"],
  ["nature-rock-smallTopA", "nature/rock_smallTopA", "habitat", "Rock small topped A", "Rocher petit sommet A"],
  ["nature-rock-smallTopB", "nature/rock_smallTopB", "habitat", "Rock small topped B", "Rocher petit sommet B"],
  ["nature-rock-tallA", "nature/rock_tallA", "habitat", "Rock tall A", "Rocher haut A"],
  ["nature-rock-tallB", "nature/rock_tallB", "habitat", "Rock tall B", "Rocher haut B"],
  ["nature-rock-tallC", "nature/rock_tallC", "habitat", "Rock tall C", "Rocher haut C"],
  ["nature-rock-tallD", "nature/rock_tallD", "habitat", "Rock tall D", "Rocher haut D"],
  ["nature-rock-tallE", "nature/rock_tallE", "habitat", "Rock tall E", "Rocher haut E"],
  ["nature-rock-tallF", "nature/rock_tallF", "habitat", "Rock tall F", "Rocher haut F"],
  ["nature-rock-tallG", "nature/rock_tallG", "habitat", "Rock tall G", "Rocher haut G"],
  ["nature-rock-tallH", "nature/rock_tallH", "habitat", "Rock tall H", "Rocher haut H"],
  ["nature-rock-tallI", "nature/rock_tallI", "habitat", "Rock tall I", "Rocher haut I"],
  ["nature-rock-tallJ", "nature/rock_tallJ", "habitat", "Rock tall J", "Rocher haut J"],
  ["nature-stone-largeA", "nature/stone_largeA", "habitat", "Stone large A", "Pierre grande A"],
  ["nature-stone-largeB", "nature/stone_largeB", "habitat", "Stone large B", "Pierre grande B"],
  ["nature-stone-largeC", "nature/stone_largeC", "habitat", "Stone large C", "Pierre grande C"],
  ["nature-stone-largeD", "nature/stone_largeD", "habitat", "Stone large D", "Pierre grande D"],
  ["nature-stone-largeE", "nature/stone_largeE", "habitat", "Stone large E", "Pierre grande E"],
  ["nature-stone-largeF", "nature/stone_largeF", "habitat", "Stone large F", "Pierre grande F"],
  ["nature-stone-smallA", "nature/stone_smallA", "habitat", "Stone small A", "Pierre petit A"],
  ["nature-stone-smallB", "nature/stone_smallB", "habitat", "Stone small B", "Pierre petit B"],
  ["nature-stone-smallC", "nature/stone_smallC", "habitat", "Stone small C", "Pierre petit C"],
  ["nature-stone-smallD", "nature/stone_smallD", "habitat", "Stone small D", "Pierre petit D"],
  ["nature-stone-smallE", "nature/stone_smallE", "habitat", "Stone small E", "Pierre petit E"],
  ["nature-stone-smallF", "nature/stone_smallF", "habitat", "Stone small F", "Pierre petit F"],
  ["nature-stone-smallFlatA", "nature/stone_smallFlatA", "habitat", "Stone small flat A", "Pierre petit plat A"],
  ["nature-stone-smallFlatB", "nature/stone_smallFlatB", "habitat", "Stone small flat B", "Pierre petit plat B"],
  ["nature-stone-smallFlatC", "nature/stone_smallFlatC", "habitat", "Stone small flat C", "Pierre petit plat C"],
  ["nature-stone-smallG", "nature/stone_smallG", "habitat", "Stone small G", "Pierre petit G"],
  ["nature-stone-smallH", "nature/stone_smallH", "habitat", "Stone small H", "Pierre petit H"],
  ["nature-stone-smallI", "nature/stone_smallI", "habitat", "Stone small I", "Pierre petit I"],
  ["nature-stone-smallTopA", "nature/stone_smallTopA", "habitat", "Stone small topped A", "Pierre petit sommet A"],
  ["nature-stone-smallTopB", "nature/stone_smallTopB", "habitat", "Stone small topped B", "Pierre petit sommet B"],
  ["nature-stone-tallA", "nature/stone_tallA", "habitat", "Stone tall A", "Pierre haut A"],
  ["nature-stone-tallB", "nature/stone_tallB", "habitat", "Stone tall B", "Pierre haut B"],
  ["nature-stone-tallC", "nature/stone_tallC", "habitat", "Stone tall C", "Pierre haut C"],
  ["nature-stone-tallD", "nature/stone_tallD", "habitat", "Stone tall D", "Pierre haut D"],
  ["nature-stone-tallE", "nature/stone_tallE", "habitat", "Stone tall E", "Pierre haut E"],
  ["nature-stone-tallF", "nature/stone_tallF", "habitat", "Stone tall F", "Pierre haut F"],
  ["nature-stone-tallG", "nature/stone_tallG", "habitat", "Stone tall G", "Pierre haut G"],
  ["nature-stone-tallH", "nature/stone_tallH", "habitat", "Stone tall H", "Pierre haut H"],
  ["nature-stone-tallI", "nature/stone_tallI", "habitat", "Stone tall I", "Pierre haut I"],
  ["nature-stone-tallJ", "nature/stone_tallJ", "habitat", "Stone tall J", "Pierre haut J"],
  ["nature-stump-old", "nature/stump_old", "habitat", "Stump old", "Souche ancienne"],
  ["nature-stump-oldTall", "nature/stump_oldTall", "habitat", "Stump old tall", "Souche ancienne haut"],
  ["nature-stump-round", "nature/stump_round", "habitat", "Stump round", "Souche rond"],
  ["nature-stump-square", "nature/stump_square", "habitat", "Stump square", "Souche carrée"],
  ["nature-tree-blocks", "nature/tree_blocks", "tree", "Tree block crown", "Arbre couronne cubique"],
  ["nature-tree-blocks-dark", "nature/tree_blocks_dark", "tree", "Tree block crown dark", "Arbre couronne cubique sombre"],
  ["nature-tree-blocks-fall", "nature/tree_blocks_fall", "tree", "Tree block crown autumn", "Arbre couronne cubique automne"],
  ["nature-tree-cone", "nature/tree_cone", "tree", "Tree conical", "Arbre conique"],
  ["nature-tree-cone-dark", "nature/tree_cone_dark", "tree", "Tree conical dark", "Arbre conique sombre"],
  ["nature-tree-cone-fall", "nature/tree_cone_fall", "tree", "Tree conical autumn", "Arbre conique automne"],
  ["nature-tree-default", "nature/tree_default", "tree", "Tree classic", "Arbre classique"],
  ["nature-tree-default-dark", "nature/tree_default_dark", "tree", "Tree classic dark", "Arbre classique sombre"],
  ["nature-tree-default-fall", "nature/tree_default_fall", "tree", "Tree classic autumn", "Arbre classique automne"],
  ["nature-tree-fat", "nature/tree_fat", "tree", "Tree broad", "Arbre large"],
  ["nature-tree-fat-darkh", "nature/tree_fat_darkh", "tree", "Tree broad dark", "Arbre large sombre"],
  ["nature-tree-fat-fall", "nature/tree_fat_fall", "tree", "Tree broad autumn", "Arbre large automne"],
  ["nature-tree-oak", "nature/tree_oak", "tree", "Tree oak", "Arbre chêne"],
  ["nature-tree-oak-dark", "nature/tree_oak_dark", "tree", "Tree oak dark", "Arbre chêne sombre"],
  ["nature-tree-oak-fall", "nature/tree_oak_fall", "tree", "Tree oak autumn", "Arbre chêne automne"],
  ["nature-tree-palm", "nature/tree_palm", "palm", "Tree palm", "Arbre palmier"],
  ["nature-tree-palmBend", "nature/tree_palmBend", "palm", "Tree palm curved", "Arbre palmier courbé"],
  ["nature-tree-palmShort", "nature/tree_palmShort", "palm", "Tree palm short", "Arbre palmier court"],
  ["nature-tree-palmTall", "nature/tree_palmTall", "palm", "Tree palm tall", "Arbre palmier haut"],
  ["nature-tree-pineDefaultA", "nature/tree_pineDefaultA", "conifer", "Tree pine classic A", "Arbre pin classique A"],
  ["nature-tree-pineDefaultB", "nature/tree_pineDefaultB", "conifer", "Tree pine classic B", "Arbre pin classique B"],
  ["nature-tree-pineGroundA", "nature/tree_pineGroundA", "conifer", "Tree pine low A", "Arbre pin bas A"],
  ["nature-tree-pineGroundB", "nature/tree_pineGroundB", "conifer", "Tree pine low B", "Arbre pin bas B"],
  ["nature-tree-pineRoundA", "nature/tree_pineRoundA", "conifer", "Tree pine round A", "Arbre pin rond A"],
  ["nature-tree-pineRoundB", "nature/tree_pineRoundB", "conifer", "Tree pine round B", "Arbre pin rond B"],
  ["nature-tree-pineRoundC", "nature/tree_pineRoundC", "conifer", "Tree pine round C", "Arbre pin rond C"],
  ["nature-tree-pineRoundD", "nature/tree_pineRoundD", "conifer", "Tree pine round D", "Arbre pin rond D"],
  ["nature-tree-pineRoundE", "nature/tree_pineRoundE", "conifer", "Tree pine round E", "Arbre pin rond E"],
  ["nature-tree-pineRoundF", "nature/tree_pineRoundF", "conifer", "Tree pine round F", "Arbre pin rond F"],
  ["nature-tree-pineSmallA", "nature/tree_pineSmallA", "conifer", "Tree pine small A", "Arbre pin petit A"],
  ["nature-tree-pineSmallB", "nature/tree_pineSmallB", "conifer", "Tree pine small B", "Arbre pin petit B"],
  ["nature-tree-pineSmallC", "nature/tree_pineSmallC", "conifer", "Tree pine small C", "Arbre pin petit C"],
  ["nature-tree-pineSmallD", "nature/tree_pineSmallD", "conifer", "Tree pine small D", "Arbre pin petit D"],
  ["nature-tree-pineTallA", "nature/tree_pineTallA", "conifer", "Tree pine tall A", "Arbre pin haut A"],
  ["nature-tree-pineTallB", "nature/tree_pineTallB", "conifer", "Tree pine tall B", "Arbre pin haut B"],
  ["nature-tree-pineTallC", "nature/tree_pineTallC", "conifer", "Tree pine tall C", "Arbre pin haut C"],
  ["nature-tree-pineTallD", "nature/tree_pineTallD", "conifer", "Tree pine tall D", "Arbre pin haut D"],
  ["nature-tree-plateau", "nature/tree_plateau", "tree", "Tree flat crown", "Arbre couronne plate"],
  ["nature-tree-plateau-dark", "nature/tree_plateau_dark", "tree", "Tree flat crown dark", "Arbre couronne plate sombre"],
  ["nature-tree-plateau-fall", "nature/tree_plateau_fall", "tree", "Tree flat crown autumn", "Arbre couronne plate automne"],
  ["nature-tree-simple", "nature/tree_simple", "tree", "Tree simple", "Arbre simple"],
  ["nature-tree-simple-dark", "nature/tree_simple_dark", "tree", "Tree simple dark", "Arbre simple sombre"],
  ["nature-tree-simple-fall", "nature/tree_simple_fall", "tree", "Tree simple autumn", "Arbre simple automne"],
  ["nature-tree-small", "nature/tree_small", "tree", "Tree small", "Arbre petit"],
  ["nature-tree-small-dark", "nature/tree_small_dark", "tree", "Tree small dark", "Arbre petit sombre"],
  ["nature-tree-small-fall", "nature/tree_small_fall", "tree", "Tree small autumn", "Arbre petit automne"],
  ["nature-tree-tall", "nature/tree_tall", "tree", "Tree tall", "Arbre haut"],
  ["nature-tree-tall-dark", "nature/tree_tall_dark", "tree", "Tree tall dark", "Arbre haut sombre"],
  ["nature-tree-tall-fall", "nature/tree_tall_fall", "tree", "Tree tall autumn", "Arbre haut automne"],
  ["nature-tree-thin", "nature/tree_thin", "tree", "Tree slender", "Arbre fin"],
  ["nature-tree-thin-dark", "nature/tree_thin_dark", "tree", "Tree slender dark", "Arbre fin sombre"],
  ["nature-tree-thin-fall", "nature/tree_thin_fall", "tree", "Tree slender autumn", "Arbre fin automne"],
  ["mini-forest-patch-grass", "mini-forest/patch-grass", "grass", "patch Grass · Mini Forest", "touffe Herbe · Mini Forest"],
  ["mini-forest-plant", "mini-forest/plant", "shrub", "Plant · Mini Forest", "Plante · Mini Forest"],
  ["mini-forest-rocks-high", "mini-forest/rocks-high", "habitat", "Rocks high · Mini Forest", "Rochers haut · Mini Forest"],
  ["mini-forest-rocks-low", "mini-forest/rocks-low", "habitat", "Rocks low · Mini Forest", "Rochers bas · Mini Forest"],
  ["mini-forest-rocks-ramp", "mini-forest/rocks-ramp", "habitat", "Rocks sloped · Mini Forest", "Rochers incliné · Mini Forest"],
  ["mini-forest-stones", "mini-forest/stones", "habitat", "Stones · Mini Forest", "Pierres · Mini Forest"],
  ["mini-forest-tree", "mini-forest/tree", "conifer", "Tree · Mini Forest", "Arbre · Mini Forest"],
  ["mini-forest-tree-high", "mini-forest/tree-high", "conifer", "Tree high · Mini Forest", "Arbre haut · Mini Forest"],
  ["pirate-grass", "pirate/grass", "grass", "Grass · Pirate", "Herbe · Pirate"],
  ["pirate-grass-patch", "pirate/grass-patch", "grass", "Grass patch · Pirate", "Herbe touffe · Pirate"],
  ["pirate-grass-plant", "pirate/grass-plant", "grass", "Grass Plant · Pirate", "Herbe Plante · Pirate"],
  ["pirate-palm-bend", "pirate/palm-bend", "palm", "palm curved · Pirate", "palmier courbé · Pirate"],
  ["pirate-palm-straight", "pirate/palm-straight", "palm", "palm straight · Pirate", "palmier droit · Pirate"],
  ["pirate-patch-grass", "pirate/patch-grass", "grass", "patch Grass · Pirate", "touffe Herbe · Pirate"],
  ["pirate-patch-grass-foliage", "pirate/patch-grass-foliage", "grass", "patch Grass foliage · Pirate", "touffe Herbe feuillage · Pirate"],
] as const satisfies readonly (readonly [string, string, NatureFamily, string, string])[];

export type NatureType = typeof NATURE_MODELS[number][0];
export type NatureModel = typeof NATURE_MODELS[number];
export const NATURE_TYPES = NATURE_MODELS.map(([type]) => type);
const modelsByType = new Map<string, NatureModel>(NATURE_MODELS.map(model => [model[0], model]));

export function natureModelOf(type: string): NatureModel | undefined {
  return modelsByType.get(type);
}

export function greenProfileOf(type: string) {
  if (type === 'tree') return { radius: 4, cooling: 1, biodiversity: 1, wellbeing: 1 };
  if (type === 'park') return { radius: 6, cooling: 3, biodiversity: 3, wellbeing: 3 };
  const model = natureModelOf(type);
  return model ? NATURE_FAMILIES[model[2]] : undefined;
}
